
--- 
title:  成功解决If this call came from a _pb2.py file, your generated code is out of date and must be regenerate 
tags: []
categories: [] 

---
成功解决If this call came from a _pb2.py file, your generated code is out of date and must be regenerate







**目录**













## **解决问题**

Exception "unhandled RuntimeError" Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback): Failed to import transformers.generation.utils because of the following
